import type { BuildStage } from "../types";
import { ToolButton } from "./Primitives";

export function Dock({ building, stage, stages, built, expanded, setExpanded, onChat, onTune, onCancel, onAssets, onBug, badges }: {
  building: boolean; stage: number; stages: BuildStage[]; built: boolean; expanded: boolean; setExpanded: (v: boolean) => void; onChat: () => void; onTune: () => void; onCancel: () => void; onAssets: () => void; onBug: () => void; badges: boolean;
}) {
  const pct = building ? Math.round((stage / stages.length) * 100) : 100;
  return <div className={`dock ${building || !built ? "solo" : ""}`}><div className={`ai-pill ${building ? "building" : "compact"} ${expanded ? "expanded" : ""}`} onClick={() => building ? setExpanded(!expanded) : onChat()}><div className="pill-main"><span className="ai-star">✦</span><span><b>{building ? stages[stage]?.label ?? "Finishing build…" : built ? "Edit with AI" : "Sekai"}</b>{building && <small>{stage > 1 ? "Tuning values ready · adjust while I paint" : <>Step {Math.min(stage + 1, stages.length)} of {stages.length} · <button className="inline-cancel" onClick={e => { e.stopPropagation(); onCancel(); }}>cancel anytime</button></>}</small>}</span>{building && stage > 1 && <button className="tune-now" onClick={e => { e.stopPropagation(); onTune(); }}>Tune now</button>}{building && <em>{expanded ? "⌄" : "⌃"}</em>}</div>{building && <><div className="stage-list">{stages.map((s, i) => <div className={i < stage ? "done" : i === stage ? "now" : ""} key={s.label}><i>{i < stage ? "✓" : i + 1}</i>{s.label}{i === 1 && stage > 1 ? <strong onClick={e => { e.stopPropagation(); onTune(); }}>Review</strong> : null}</div>)}</div><div className="progress"><span>{pct}%</span><i style={{ width: `${pct}%` }} /></div></>}</div>{built && !building && <div className="dock-tools"><ToolButton icon="bug" label="Bug" onClick={onBug} /><ToolButton icon="tune" label="Tune" onClick={onTune} /><ToolButton icon="image" label="Images" badge={badges ? 2 : 0} onClick={onAssets} /><ToolButton icon="music" label="Music" badge={badges ? 1 : 0} onClick={onAssets} /></div>}</div>;
}
